"""Git hooks, CI templates, and other infrastructure helpers.

Top-level module; no downstream imports within _wf_* are needed here.
"""
from __future__ import annotations

import shlex
import stat
from pathlib import Path

from ._types import (
    Finding,
    _green,
    _bold,
)


# ── Git hooks ─────────────────────────────────────────────────────────────────

def pre_commit_hook_text(root: Path) -> str:
    root_arg = root.as_posix()
    command = f"ssd-core guard --root {shlex.quote(root_arg)} --require-active-change --strict-state"
    return "\n".join(
        [
            "#!/bin/sh",
            "# Generated by SSD-Core. Edit with care.",
            command,
            "",
        ]
    )


def pre_push_hook_text(root: Path) -> str:
    root_arg = root.as_posix()
    command = f"ssd-core guard --root {shlex.quote(root_arg)} --strict-state"
    return "\n".join(
        [
            "#!/bin/sh",
            "# Generated by SSD-Core. Edit with care.",
            command,
            "",
        ]
    )


def install_hooks(root: Path) -> list[Finding]:
    git_dir = root / ".git"
    if not git_dir.is_dir():
        return [Finding("error", git_dir, "git repository is required to install hooks")]

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)

    pre_commit = hooks_dir / "pre-commit"
    pre_commit.write_text(pre_commit_hook_text(root), encoding="utf-8")
    try:
        pre_commit.chmod(0o755)
    except OSError:
        pass
    print(f"Installed SSD-Core pre-commit hook: {pre_commit.as_posix()}")

    pre_push = hooks_dir / "pre-push"
    pre_push.write_text(pre_push_hook_text(root), encoding="utf-8")
    try:
        pre_push.chmod(0o755)
    except OSError:
        pass
    print(f"Installed SSD-Core pre-push hook: {pre_push.as_posix()}")

    return []


# ── CI templates ──────────────────────────────────────────────────────────────

_GITHUB_ACTIONS_TEMPLATE = """\
name: SDD Governance Guard

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  sdd-guard:
    name: SDD governance check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install SDD-Core
        run: pip install ssd-core

      - name: SDD governance guard
        run: ssd-core guard --root . --strict-state

      # Uncomment to require passing execution evidence for verified changes:
      # - name: SDD evidence guard
      #   run: ssd-core guard --root . --strict-state --require-execution-evidence
"""

_GITLAB_CI_TEMPLATE = """\
sdd-governance-guard:
  stage: test
  image: python:3.11-slim
  script:
    - pip install ssd-core
    - ssd-core guard --root . --strict-state
  # Uncomment to require passing execution evidence:
  # - ssd-core guard --root . --strict-state --require-execution-evidence
"""

_CI_TEMPLATES: dict[str, tuple[str, str]] = {
    "github-actions": (_GITHUB_ACTIONS_TEMPLATE, ".github/workflows/sdd-guard.yml"),
    "gitlab-ci":      (_GITLAB_CI_TEMPLATE,       ".gitlab-ci-sdd.yml"),
}


def write_ci_template(root: Path, template_type: str) -> list[Finding]:
    """Write a CI template file for *template_type* under *root*."""
    if template_type not in _CI_TEMPLATES:
        choices = ", ".join(sorted(_CI_TEMPLATES))
        return [Finding("error", None, f"unknown CI template type: {template_type}; choose from: {choices}")]

    content, relative_dest = _CI_TEMPLATES[template_type]
    destination = root / Path(relative_dest)
    if destination.exists():
        return [Finding("error", destination, f"CI template already exists: {relative_dest}")]

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content.lstrip(), encoding="utf-8")
    print(_green("\u2714") + f" CI template written: {_bold(relative_dest)}")
    print(f"  type    : {template_type}")
    print(f"  path    : {relative_dest}")
    print(f"  next    : commit this file, then enable CI in your repository")
    return []
